/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void negras_click(GOption source, GEvent event) { //_CODE_:negras:451200:
  negras.setSelected(true);
  println("option1 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:negras:451200:

public void blancas_click(GOption source, GEvent event) { //_CODE_:blancas:688855:
  println("option2 - GOption >> GEvent." + event + " @ " + millis());
  blancas.setSelected(true);
} //_CODE_:blancas:688855:

public void dosjugador_click(GOption source, GEvent event) { //_CODE_:dosjugador:871251:
  println("option3 - GOption >> GEvent." + event + " @ " + millis());
  dosjugador.setSelected(true);
} //_CODE_:dosjugador:871251:

public void nivel1_click(GOption source, GEvent event) { //_CODE_:nivel1:299804:
  nivel1.setSelected(true);
  println("option1 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:nivel1:299804:

public void nivel2_click(GOption source, GEvent event) { //_CODE_:nivel2:682635:
nivel2.setSelected(true);
  println("option2 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:nivel2:682635:

public void nivel3_click(GOption source, GEvent event) { //_CODE_:nivel3:792702:
nivel3.setSelected(true);
  println("option3 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:nivel3:792702:

public void nivel4_click(GOption source, GEvent event) { //_CODE_:nivel4:935769:
nivel4.setSelected(true);
  println("option4 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:nivel4:935769:

public void veinte_click(GOption source, GEvent event) { //_CODE_:veinte:960829:
  veinte.setSelected(true);
  println("veinte - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:veinte:960829:

public void treinta_click(GOption source, GEvent event) { //_CODE_:treinta:823849:
treinta.setSelected(true);
  println("option2 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:treinta:823849:

public void cuarenta_click(GOption source, GEvent event) { //_CODE_:cuarenta:449219:
cuarenta.setSelected(true);
  println("option3 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:cuarenta:449219:

public void sinlim_click(GOption source, GEvent event) { //_CODE_:sinlim:378321:
sinlim.setSelected(true);
  println("option4 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:sinlim:378321:

public void blancasnom_change(GTextField source, GEvent event) { //_CODE_:blancasnom:606894:
  println("blancasnom - GTextField >> GEvent." + event + " @ " + millis());
  blancasnom.getText();
} //_CODE_:blancasnom:606894:

public void negrasnom_change(GTextField source, GEvent event) { //_CODE_:negrasnom:805281:
  println("negrasnom - GTextField >> GEvent." + event + " @ " + millis());
  negrasnom.getText();
} //_CODE_:negrasnom:805281:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  modo = new GToggleGroup();
  negras = new GOption(this, 70, 120, 200, 16);
  negras.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  negras.setText("Jugar con negras");
  negras.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  negras.setOpaque(false);
  negras.addEventHandler(this, "negras_click");
  blancas = new GOption(this, 70, 136, 200, 16);
  blancas.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  blancas.setText("Jugar con blancas");
  blancas.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  blancas.setOpaque(false);
  blancas.addEventHandler(this, "blancas_click");
  dosjugador = new GOption(this, 70, 154, 200, 16);
  dosjugador.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  dosjugador.setText("Dos jugadores");
  dosjugador.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  dosjugador.setOpaque(false);
  dosjugador.addEventHandler(this, "dosjugador_click");
  modo.addControl(negras);
  negras.setSelected(true);
  modo.addControl(blancas);
  modo.addControl(dosjugador);
  dificultad = new GToggleGroup();
  nivel1 = new GOption(this, 70, 184, 120, 16);
  nivel1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  nivel1.setText("Nivel 1");
  nivel1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  nivel1.setOpaque(false);
  nivel1.addEventHandler(this, "nivel1_click");
  nivel2 = new GOption(this, 70, 200, 120, 16);
  nivel2.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  nivel2.setText("Nivel 2");
  nivel2.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  nivel2.setOpaque(false);
  nivel2.addEventHandler(this, "nivel2_click");
  nivel3 = new GOption(this, 190, 184, 120, 16);
  nivel3.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  nivel3.setText("Nivel 3");
  nivel3.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  nivel3.setOpaque(false);
  nivel3.addEventHandler(this, "nivel3_click");
  nivel4 = new GOption(this, 192, 200, 120, 16);
  nivel4.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  nivel4.setText("Nivel 4");
  nivel4.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  nivel4.setOpaque(false);
  nivel4.addEventHandler(this, "nivel4_click");
  dificultad.addControl(nivel1);
  nivel1.setSelected(true);
  dificultad.addControl(nivel2);
  dificultad.addControl(nivel3);
  dificultad.addControl(nivel4);
  limite = new GToggleGroup();
  veinte = new GOption(this, 70, 230, 120, 16);
  veinte.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  veinte.setText("20 Minutos");
  veinte.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  veinte.setOpaque(false);
  veinte.addEventHandler(this, "veinte_click");
  treinta = new GOption(this, 70, 246, 120, 16);
  treinta.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  treinta.setText("30 Minutos");
  treinta.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  treinta.setOpaque(false);
  treinta.addEventHandler(this, "treinta_click");
  cuarenta = new GOption(this, 192, 230, 120, 16);
  cuarenta.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  cuarenta.setText("40 Minutos");
  cuarenta.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  cuarenta.setOpaque(false);
  cuarenta.addEventHandler(this, "cuarenta_click");
  sinlim = new GOption(this, 192, 246, 120, 16);
  sinlim.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  sinlim.setText("Sin limite");
  sinlim.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  sinlim.setOpaque(false);
  sinlim.addEventHandler(this, "sinlim_click");
  limite.addControl(veinte);
  veinte.setSelected(true);
  limite.addControl(treinta);
  limite.addControl(cuarenta);
  limite.addControl(sinlim);
  blancasnom = new GTextField(this, 70, 281, 160, 16, G4P.SCROLLBARS_NONE);
  blancasnom.setPromptText("Blancas");
  blancasnom.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  blancasnom.setOpaque(false);
  blancasnom.addEventHandler(this, "blancasnom_change");
  negrasnom = new GTextField(this, 70, 298, 160, 16, G4P.SCROLLBARS_NONE);
  negrasnom.setPromptText("Negras");
  negrasnom.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  negrasnom.setOpaque(false);
  negrasnom.addEventHandler(this, "negrasnom_change");
}

// Variable declarations 
// autogenerated do not edit
GToggleGroup modo; 
GOption negras; 
GOption blancas; 
GOption dosjugador; 
GToggleGroup dificultad; 
GOption nivel1; 
GOption nivel2; 
GOption nivel3; 
GOption nivel4; 
GToggleGroup limite; 
GOption veinte; 
GOption treinta; 
GOption cuarenta; 
GOption sinlim; 
GTextField blancasnom; 
GTextField negrasnom; 